---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: appx-cloud-com
  namespace: ingress
spec:
  secretName: appx-cloud-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.appx-cloud.com"
  dnsNames:
  - "appx-cloud.com"
  - "*.appx-cloud.com"
